In [1]:
import pandas as pd

## Data Gathering

In [2]:
data= pd.read_csv('huge_1M_titanic.csv')

## Data Pre-Processing

In [3]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1310,1,1,"Name1310, Miss. Surname1310",female,NaN,0,0,SOTON/O2 3101272,76.760165,NaN,C
1,1311,0,3,"Name1311, Col. Surname1311",male,29.0,0,0,223596,10.193097,NaN,S
2,1312,0,3,"Name1312, Mr. Surname1312",male,20.0,0,0,54636,12.029416,C83,C
3,1313,0,3,"Name1313, Mr. Surname1313",male,27.0,0,0,PC 17760,13.429448,NaN,S
4,1314,0,3,"Name1314, Mr. Surname1314",male,32.0,0,0,364512,4.840769,E33,C

In [4]:
data.shape

(1000000, 12)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PassengerId  1000000 non-null  int64
 1   Survived     1000000 non-null  int64
 2   Pclass       1000000 non-null  int64
 3   Name         1000000 non-null  object
 4   Sex          1000000 non-null  object
 5   Age          801400 non-null   float64
 6   SibSp        1000000 non-null  int64
 7   Parch        1000000 non-null  int64
 8   Ticket       1000000 non-null  object
 9   Fare         1000000 non-null  float64
 10  Cabin        229805 non-null   object
 11  Embarked     997760 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 91.6+ MB

### Missing Values

In [6]:
data.isnull().sum()

PassengerId         0
Survived            0
Pclass              0
Name                0
Sex                 0
Age            198600
SibSp               0
Parch               0
Ticket              0
Fare                0
Cabin          770195
Embarked         2240
dtype: int64

In [7]:
## removing "Age" as it is having lot's of missing values. If required can be filled with avergae value of the available ages
data=data.drop(columns=['PassengerId','Name','Age','Ticket','Cabin'])

In [8]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare Embarked
0         1       1  female      0      0  76.760165        C
1         0       3    male      0      0  10.193097        S
2         0       3    male      0      0  12.029416        C
3         0       3    male      0      0  13.429448        S
4         0       3    male      0      0   4.840769        C

In [9]:
data.isnull().sum()

Survived       0
Pclass         0
Sex            0
SibSp          0
Parch          0
Fare           0
Embarked    2240
dtype: int64

In [10]:
## Check from which port most people embarked
## Since Embarked is Categorical column use mode, else use mean in case of numerical column
data['Embarked'].mode()

0    S
Name: Embarked, dtype: object

In [11]:
data['Embarked'].value_counts()

Embarked
S    729468
C    186846
Q     81446
Name: count, dtype: int64

## Data Cleaning

In [12]:
data['Embarked']=data['Embarked'].replace({'S':'Southampton','C':'Cheboug','Q':'Queenstown'})

In [13]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare     Embarked
0         1       1  female      0      0  76.760165      Cheboug
1         0       3    male      0      0  10.193097  Southampton
2         0       3    male      0      0  12.029416      Cheboug
3         0       3    male      0      0  13.429448  Southampton
4         0       3    male      0      0   4.840769      Cheboug

In [14]:
data['Embarked'].value_counts()

Embarked
Southampton    729468
Cheboug        186846
Queenstown      81446
Name: count, dtype: int64

### Remove rows those don't have embarked value

In [15]:
data.dropna(subset=['Embarked'],inplace=True)

In [16]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [17]:
data.shape

(997760, 7)

In [18]:
data['Fare'] = data['Fare'].astype('int8')

In [19]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch  Fare     Embarked
0         1       1  female      0      0    76      Cheboug
1         0       3    male      0      0    10  Southampton
2         0       3    male      0      0    12      Cheboug
3         0       3    male      0      0    13  Southampton
4         0       3    male      0      0     4      Cheboug

In [20]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

## Feature Encoding

In [21]:
## Encode Sex --> LabelEncoder
from sklearn.preprocessing import LabelEncoder

In [22]:
label=LabelEncoder()

In [23]:
data['Sex'] = label.fit_transform(data['Sex'])

In [24]:
data.head()

   Survived  Pclass  Sex  SibSp  Parch  Fare     Embarked
0         1       1    0      0      0    76      Cheboug
1         0       3    1      0      0    10  Southampton
2         0       3    1      0      0    12      Cheboug
3         0       3    1      0      0    13  Southampton
4         0       3    1      0      0     4      Cheboug

In [25]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [26]:
## Encode Embarked --> OneHotEncoder
from sklearn.preprocessing import OneHotEncoder

In [27]:
ohe = OneHotEncoder(sparse_output=False)

In [28]:
embarked = ohe.fit_transform(data[['Embarked']])

In [29]:
## create data frame of the encoded embarked data
embarked_df = pd.DataFrame(embarked,columns=ohe.get_feature_names_out())

In [30]:
embarked_df

        Embarked_Cheboug  Embarked_Queenstown  Embarked_Southampton
0                    1.0                  0.0                   0.0
1                    0.0                  0.0                   1.0
2                    1.0                  0.0                   0.0
3                    0.0                  0.0                   1.0
4                    1.0                  0.0                   0.0
...                  ...                  ...                   ...
997755               0.0                  0.0                   1.0
997756               0.0                  0.0                   1.0
997757               0.0                  0.0                   1.0
997758               0.0                  0.0                   1.0
997759               0.0                  0.0                   1.0

[997760 rows x 3 columns]

In [31]:
embarked_df.shape

(997760, 3)

In [32]:
embarked_df.isnull().sum()

Embarked_Cheboug        0
Embarked_Queenstown     0
Embarked_Southampton    0
dtype: int64

In [33]:
## join the data frames
data = pd.concat([data.drop(columns=['Embarked']),embarked_df],axis=1)

In [34]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cheboug,Embarked_Queenstown,Embarked_Southampton
0,1.0,1.0,0.0,0.0,0.0,76.0,1.0,0.0,0.0
1,0.0,3.0,1.0,0.0,0.0,10.0,0.0,0.0,1.0
2,0.0,3.0,1.0,0.0,0.0,12.0,1.0,0.0,0.0
3,0.0,3.0,1.0,0.0,0.0,13.0,0.0,0.0,1.0
4,0.0,3.0,1.0,0.0,0.0,4.0,1.0,0.0,0.0

In [35]:
data.isnull().sum()

Survived                2234
Pclass                  2234
Sex                     2234
SibSp                   2234
Parch                   2234
Fare                    2234
Embarked_Cheboug        2234
Embarked_Queenstown     2234
Embarked_Southampton    2234
dtype: int64

## Feature Scaling - column's mean value should come as 0 and std dev as 1

In [36]:
### Standarization & Normalization are 2 ways for scaling

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
scale = StandardScaler()

In [39]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare',
       'Embarked_Cheboug', 'Embarked_Queenstown', 'Embarked_Southampton'],
      dtype='object')

In [40]:
num_cols=['Pclass', 'SibSp', 'Parch', 'Fare']

In [41]:
data[num_cols] = scale.fit_transform(data[num_cols])

In [42]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cheboug,Embarked_Queenstown,Embarked_Southampton
0,1.0,-1.568865,0.0,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.0,0.824107,1.0,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.0,0.824107,1.0,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.0,0.824107,1.0,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.0,0.824107,1.0,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [43]:
data.isnull().sum()

Survived                2234
Pclass                  2234
Sex                     2234
SibSp                   2234
Parch                   2234
Fare                    2234
Embarked_Cheboug        2234
Embarked_Queenstown     2234
Embarked_Southampton    2234
dtype: int64

In [44]:
import pickle

In [45]:
data = data.dropna()

In [46]:
with open('classificiation_label_encoder.pkl','wb') as file:
    pickle.dump(label,file)

In [47]:
with open('classificiation_one_hot_encoder.pkl','wb') as file:
    pickle.dump(ohe,file)

In [48]:
with open('classificiation_scaler.pkl','wb') as file:
    pickle.dump(scale,file)

## Train / Test / Val Split

In [49]:
## Input Columns - Drop the result colum
x=data.drop(columns=['Survived'])

In [50]:
x.head()

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cheboug,Embarked_Queenstown,Embarked_Southampton
0,-1.568865,0.0,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.824107,1.0,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.824107,1.0,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.824107,1.0,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.824107,1.0,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [51]:
x.isnull().sum()

Pclass                  0
Sex                     0
SibSp                   0
Parch                   0
Fare                    0
Embarked_Cheboug        0
Embarked_Queenstown     0
Embarked_Southampton    0
dtype: int64

In [52]:
## Output Column
y=data['Survived']

In [53]:
y.head()

0    1.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Survived, dtype: float64

In [54]:
y.isnull().sum()

np.int64(0)

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=20,random_state=42)

In [57]:
## Validation data
x_train,x_val,y_train,y_val = train_test_split(x_train,y_train,test_size=0.2,random_state=42)

In [58]:
x_val.shape

(199102, 8)

In [59]:
x_train.isnull().sum()

Pclass                  0
Sex                     0
SibSp                   0
Parch                   0
Fare                    0
Embarked_Cheboug        0
Embarked_Queenstown     0
Embarked_Southampton    0
dtype: int64

In [60]:
y_train.isnull().sum()

np.int64(0)

In [61]:
import tensorflow

In [62]:
# Deep learning is sequential hence the Sequential model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense # Hidden layer
# stop early if the loss function or acurracy is not changing even after changing epochs, this remain same
from tensorflow.keras.callbacks import EarlyStopping

In [63]:
## Input nodes should be same as the number of inpur features (columns)
(x_train.shape[1],)

(8,)

In [64]:
#model = Sequential([
# Dense(64,input_shape=(x_train.shape[1],),activation='relu'), #First Hidden layer
# Dense(32,activation='relu'), # second hidden layer
# Dense(1,activation='sigmoid') # output layer, as this is binary classification activation function on output is sigmoid
# ])

In [65]:
model = Sequential([Dense(64,input_shape=(x_train.shape[1],),activation='relu'),
        Dense(32,activation='relu'), 
        Dense(1,activation='sigmoid')]   )

f:\TuteDude\DeepLearning\ANN\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [66]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,689 (10.50 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

## Model Compilation --> Optimizer, Loss, Metrics

In [67]:
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [68]:
## loss function is binary_crossentropy as this a binary classification problem
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [69]:
# monitor -> validation loss
# patience -> when to stop (epoch)
stopping_callback = EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [70]:
model.fit(x_train,y_train,validation_data=(x_val,y_val),epochs=100,callbacks=[stopping_callback])

Epoch 1/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 45s 2ms/step - accuracy: 0.8450 - loss: 0.3504 - val_accuracy: 0.8511 - val_loss: 0.3358
Epoch 2/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.8503 - loss: 0.3394 - val_accuracy: 0.8511 - val_loss: 0.3346
Epoch 3/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.8507 - loss: 0.3375 - val_accuracy: 0.8549 - val_loss: 0.3353
Epoch 4/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.8513 - loss: 0.3372 - val_accuracy: 0.8510 - val_loss: 0.3334
Epoch 5/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.8512 - loss: 0.3362 - val_accuracy: 0.8523 - val_loss: 0.3349
Epoch 6/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 90s 2ms/step - accuracy: 0.8517 - loss: 0.3357 - val_accuracy: 0.8536 - val_loss: 0.3340
Epoch 7/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.8515 - loss: 0.3356 - val_accuracy: 0.8544 - val_loss: 0.3311
Epoch 8/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.8515 - loss: 0.3352 - val_accuracy: 0.8537 - val_loss: 0.3303
Epoch 9/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.8514 - loss: 0.3357 - val_accuracy: 0.8533 - val_loss: 0.3323
Epoch 10/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.8517 - loss: 0.3352 - val_accuracy: 0.8549 - val_loss: 0.3292
Epoch 11/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.8524 - loss: 0.3347 - val_accuracy: 0.8550 - val_loss: 0.3297
Epoch 12/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.8526 - loss: 0.3345 - val_accuracy: 0.8538 - val_loss: 0.3310
Epoch 13/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.8524 - loss: 0.3343 - val_accuracy: 0.8560 - val_loss: 0.3288
Epoch 14/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.8523 - loss: 0.3345 - val_accuracy: 0.8534 - val_loss: 0.3294
Epoch 15/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.8519 - loss: 0.3350 - val_accuracy: 0.8496 - val_loss: 0.3325
Epoch 16/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.8518 - loss: 0.3349 - val_accuracy: 0.8511 - val_loss: 0.3333
Epoch 17/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.8516 - loss: 0.3350 - val_accuracy: 0.8548 - val_loss: 0.3309
Epoch 18/100
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.8518 - loss: 0.3347 - val_accuracy: 0.8545 - val_loss: 0.3305

In [71]:
# store in h5 format to maintain the original formats of the weights
model.save('classification_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.