In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('ai_dev_productivity.csv')

In [3]:
data.shape

(500, 9)

In [4]:
data.head()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
0,5.99,600,1,5.8,2,1,0.71,5.4,1
1,4.72,568,2,6.9,5,3,1.75,4.7,1
2,6.30,560,1,8.9,2,0,2.27,2.2,1
3,8.05,600,7,6.3,9,5,1.40,5.9,0
4,4.53,421,6,6.9,4,0,1.26,6.3,1

In [5]:
data.isnull().sum()

hours_coding        0
coffee_intake_mg    0
distractions        0
sleep_hours         0
commits             0
bugs_reported       0
ai_usage_hours      0
cognitive_load      0
task_success        0
dtype: int64

In [6]:
data.duplicated().sum()

np.int64(0)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hours_coding      500 non-null    float64
 1   coffee_intake_mg  500 non-null    int64
 2   distractions      500 non-null    int64
 3   sleep_hours       500 non-null    float64
 4   commits           500 non-null    int64
 5   bugs_reported     500 non-null    int64
 6   ai_usage_hours    500 non-null    float64
 7   cognitive_load    500 non-null    float64
 8   task_success      500 non-null    int64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB

In [8]:
data.describe()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
count,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000,500.000000
mean,5.015600,463.192000,2.976000,6.975800,4.60800,0.858000,1.510920,4.498200,0.606000
std,1.947253,142.334991,1.678409,1.455965,2.70499,1.102846,1.085557,1.868861,0.489124
min,0.000000,6.000000,0.000000,3.000000,0.00000,0.000000,0.000000,1.000000,0.000000
25%,3.600000,369.500000,2.000000,6.100000,3.00000,0.000000,0.697500,3.175000,0.000000
50%,5.030000,500.500000,3.000000,6.950000,5.00000,0.000000,1.260000,4.400000,1.000000
75%,6.275000,600.000000,4.000000,7.900000,6.00000,2.000000,2.070000,5.800000,1.000000
max,12.000000,600.000000,8.000000,10.000000,13.00000,5.000000,6.360000,10.000000,1.000000

### No Ecoding required as all columns are numeric only Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

In [10]:
x = data.drop(columns=['cognitive_load'])
y = data['cognitive_load']

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state=42)

In [12]:
x_train.shape

(400, 8)

In [13]:
y_train.shape

(400,)

In [14]:
x.columns

Index(['hours_coding', 'coffee_intake_mg', 'distractions', 'sleep_hours',
       'commits', 'bugs_reported', 'ai_usage_hours', 'task_success'],
      dtype='object')

In [15]:
x_train[['hours_coding', 'coffee_intake_mg', 'distractions', 'sleep_hours',
       'commits', 'bugs_reported', 'ai_usage_hours']] = scale.fit_transform(x_train[['hours_coding', 'coffee_intake_mg', 'distractions', 'sleep_hours',
       'commits', 'bugs_reported', 'ai_usage_hours']])

In [16]:
x_train

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,task_success
249,0.410116,0.348814,-1.159772,1.628183,0.146206,-0.780969,0.050837,1
433,0.731716,0.508152,1.222301,-0.459879,-1.334364,-0.780969,0.634796,1
19,-1.442912,-1.424697,0.031265,-2.211156,-0.594079,-0.780969,-0.778007,0
322,-0.840550,-0.066853,0.031265,-0.527236,-0.964221,1.927593,0.493516,0
332,0.073202,0.030136,1.222301,-0.729306,-0.594079,-0.780969,0.465260,0
...,...,...,...,...,...,...,...,...
106,1.921126,0.965386,-0.564254,0.348403,0.146206,-0.780969,-0.420097,1
270,1.466802,0.965386,2.413338,1.224042,1.256634,-0.780969,0.041419,1
348,-0.738455,-0.946681,-0.564254,-0.594592,-0.223936,1.024739,-1.201848,0
435,0.073202,0.203330,-0.564254,1.156685,1.256634,-0.780969,-0.307073,1
102,-0.355598,0.099414,-1.159772,-0.998733,-0.594079,-0.780969,-0.373004,1

In [19]:
x_test[['hours_coding', 'coffee_intake_mg', 'distractions', 'sleep_hours',
       'commits', 'bugs_reported', 'ai_usage_hours']] = scale.transform(x_test[['hours_coding', 'coffee_intake_mg', 'distractions', 'sleep_hours',
       'commits', 'bugs_reported', 'ai_usage_hours']])

In [20]:
x_test

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,task_success
361,-1.828182,-3.558789,-1.891908,-6.570229,-1.382782,-0.623858,0.960957,0
73,-1.811372,-3.558789,-2.253977,-5.945405,-1.109394,-1.485110,-1.465624,1
374,-1.480785,-3.558789,-2.616047,-5.661394,-1.109394,-1.485110,-1.097505,1
155,-3.088895,-3.572409,-1.891908,-4.752560,-1.656171,-0.623858,-1.796180,0
104,-2.777919,-3.565145,-2.253977,-5.263779,-1.109394,0.237395,-1.728567,1
...,...,...,...,...,...,...,...,...
347,-3.475514,-3.573487,-2.253977,-3.957329,-1.929559,-1.485110,-2.397191,0
86,-2.175578,-3.558789,-2.253977,-6.059010,-1.792865,0.237395,-2.374653,1
75,-2.228808,-3.561399,-2.616047,-6.002208,-1.656171,-1.485110,-0.797000,1
438,-3.643609,-3.583078,-1.529838,-5.036571,-2.202948,-1.485110,-2.427242,0
15,-3.002046,-3.568720,-1.891908,-6.229416,-1.519477,-1.485110,-2.307040,0

In [22]:
(x_train.shape[1],)

(8,)

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [23]:
model = Sequential([
    Dense(64,input_shape=(x_train.shape[1],),activation='linear'),
    Dense(32,activation='linear'),
    Dense(1,activation='linear')
])

f:\TuteDude\DeepLearning\ANN\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,689 (10.50 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam',metrics=['mae'],loss='mse')

In [28]:
model.fit(x_train,y_train,epochs=100)

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0350 - loss: 1.0477 - mae: 0.8105
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0325 - loss: 0.9984 - mae: 0.7931
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.0030 - mae: 0.7967
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 0.9947 - mae: 0.7852
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0325 - loss: 0.9989 - mae: 0.7947
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9957 - mae: 0.7895
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.0090 - mae: 0.7950
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 0.9893 - mae: 0.7842
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9948 - mae: 0.7894
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9948 - mae: 0.7897
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9875 - mae: 0.7886
Epoch 12/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0350 - loss: 1.0145 - mae: 0.7973
Epoch 13/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 1.0059 - mae: 0.7978
Epoch 14/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 0.9785 - mae: 0.7839
Epoch 15/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 0.9883 - mae: 0.7858
Epoch 16/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9787 - mae: 0.7856
Epoch 17/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9719 - mae: 0.7807
Epoch 18/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9822 - mae: 0.7848
Epoch 19/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9776 - mae: 0.7795
Epoch 20/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9875 - mae: 0.7840
Epoch 21/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9972 - mae: 0.7902
Epoch 22/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9949 - mae: 0.7906
Epoch 23/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0350 - loss: 0.9911 - mae: 0.7836
Epoch 24/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 1.0005 - mae: 0.7952
Epoch 25/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0350 - loss: 0.9990 - mae: 0.7961
Epoch 26/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 0.9815 - mae: 0.7839
Epoch 27/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 1.0027 - mae: 0.7915
Epoch 28/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0350 - loss: 0.9987 - mae: 0.7901
Epoch 29/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 0.9835 - mae: 0.7836
Epoch 30/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9897 - mae: 0.7887
Epoch 31/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.0005 - mae: 0.7940
Epoch 32/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9914 - mae: 0.7883
Epoch 33/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0325 - loss: 0.9851 - mae: 0.7855
Epoch 34/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9780 - mae: 0.7843
Epoch 35/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9956 - mae: 0.7923
Epoch 36/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 0.9970 - mae: 0.7884
Epoch 37/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9803 - mae: 0.7840
Epoch 38/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 0.9795 - mae: 0.7841
Epoch 39/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9965 - mae: 0.7855
Epoch 40/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 0.9992 - mae: 0.7873
Epoch 41/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0350 - loss: 1.0206 - mae: 0.8024
Epoch 42/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0325 - loss: 0.9793 - mae: 0.7828
Epoch 43/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0350 - loss: 0.9790 - mae: 0.7828
Epoch 44/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 0.9892 - mae: 0.7888
Epoch 45/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9780 - mae: 0.7817
Epoch 46/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9934 - mae: 0.7883
Epoch 47/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 1.0049 - mae: 0.7938
Epoch 48/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9953 - mae: 0.7932
Epoch 49/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.0105 - mae: 0.7961
Epoch 50/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9829 - mae: 0.7860
Epoch 51/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9986 - mae: 0.7945
Epoch 52/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 0.9942 - mae: 0.7867
Epoch 53/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 1.0055 - mae: 0.7935
Epoch 54/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.0120 - mae: 0.7957
Epoch 55/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 0.9966 - mae: 0.7946
Epoch 56/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.0075 - mae: 0.7971
Epoch 57/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9875 - mae: 0.7894
Epoch 58/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9980 - mae: 0.7934
Epoch 59/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9927 - mae: 0.7872
Epoch 60/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9868 - mae: 0.7876
Epoch 61/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9782 - mae: 0.7819
Epoch 62/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 1.0048 - mae: 0.7966
Epoch 63/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9931 - mae: 0.7887
Epoch 64/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9795 - mae: 0.7846
Epoch 65/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9838 - mae: 0.7864
Epoch 66/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 0.9791 - mae: 0.7811
Epoch 67/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9954 - mae: 0.7914
Epoch 68/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 1.0232 - mae: 0.8005
Epoch 69/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9762 - mae: 0.7813
Epoch 70/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9930 - mae: 0.7909
Epoch 71/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0350 - loss: 1.0025 - mae: 0.7918
Epoch 72/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9967 - mae: 0.7905
Epoch 73/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.0058 - mae: 0.7919
Epoch 74/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 1.0184 - mae: 0.7996
Epoch 75/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9945 - mae: 0.7923
Epoch 76/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9853 - mae: 0.7862
Epoch 77/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9897 - mae: 0.7875
Epoch 78/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9769 - mae: 0.7801
Epoch 79/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9807 - mae: 0.7863
Epoch 80/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9931 - mae: 0.7893
Epoch 81/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9798 - mae: 0.7837
Epoch 82/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.0055 - mae: 0.7976
Epoch 83/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.0227 - mae: 0.8044
Epoch 84/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.0044 - mae: 0.7986
Epoch 85/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0350 - loss: 0.9786 - mae: 0.7804
Epoch 86/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.0021 - mae: 0.7989
Epoch 87/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.0088 - mae: 0.7969
Epoch 88/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9837 - mae: 0.7844
Epoch 89/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0350 - loss: 0.9887 - mae: 0.7901
Epoch 90/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 1.0128 - mae: 0.7982
Epoch 91/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9877 - mae: 0.7912
Epoch 92/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 0.9894 - mae: 0.7870
Epoch 93/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.0194 - mae: 0.8018
Epoch 94/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9955 - mae: 0.7967
Epoch 95/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9885 - mae: 0.7900
Epoch 96/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9753 - mae: 0.7793
Epoch 97/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 0.9904 - mae: 0.7867
Epoch 98/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 1.0052 - mae: 0.7947
Epoch 99/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.0013 - mae: 0.7938
Epoch 100/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0325 - loss: 1.0105 - mae: 0.7959